language: python

python:
        - 3.3
        - 3.4
        - 3.5
        - 3.6
        - pypy3

install:
        - pip install codecov
        - python setup.py develop

script: py.test --cov=. tests/

after_success:
        - codecov

