language: python

os:
        - linux
        - osx
        - windows

python:
        - 3.2
        - 3.3
        - 3.4
        - 3.5
        - 3.6
        - pypy3

install:
        - pip install codecov
        - pip install pytest-cov
        - python setup.py develop

script: py.test --cov=./watch/ tests/

after_success:
        - codecov

